In [22]:
#import libraries
import pandas as pd
import numpy as np
from textblob import TextBlob 
import re

In [5]:
#read excel file
tweets = pd.read_excel("sapuratweets.xlsx")

In [7]:
#show first 5 rows
tweets.head()

,Unnamed: 0,datetime,time,is_reply,is_retweet,medias,nbr_favorite,nbr_reply,nbr_retweet,text,url,user_id,usernameTweet
0,0,2018-06-01,04:17:57,False,False,NaN,0,0,0,Typically your 6th sense is the best indicator...,/RakBukuIkhwan/status/1002283057292886016,996819257227857920,RakBukuIkhwan
1,1,2018-06-22,21:08:30,False,False,NaN,2,0,1,# SapuraEnergy in nine #offshore deals worth...,/offshoreenergyt/status/1010147515876995073,125821523,offshoreenergyt
2,2,2018-06-23,18:20:19,False,False,['https://t.co/Oh7fBVGUkU'],0,0,0,# NewsUpdate : #SapuraEnergy bags contracts w...,/EnergyDais/status/1010467581218598912,892323207750926336,EnergyDais
3,3,2018-07-09,00:06:13,False,False,NaN,0,0,0,# zurieeahmadconcepts crew dubbed as #hokacre...,/strogayah/status/1015990446001217536,90175802,strogayah
4,4,2018-07-09,21:56:08,False,False,NaN,0,0,0,09/07/2018 - “ Great things in business are ne...,/syazwanHairey/status/1016320097835773952,161169232,syazwanHairey

In [26]:
#Utility function to clean tweet text by removing links, special characters using simple regex statements. 
def clean_tweet(tweet): 
    return ' '.join(re.sub("(@[A-Za-z0-9]+)|([^0-9A-Za-z \t])|(\w+:\/\/\S+)", " ", tweet).split())

In [27]:
#Utility function to classify sentiment of passed tweet using textblob's sentiment method 
def get_tweet_sentiment(tweet): 
# create TextBlob object of passed tweet text 
    analysis = TextBlob(clean_tweet(tweet)) 
# set sentiment 
    if analysis.sentiment.polarity > 0: 
        return 'positive'
    elif analysis.sentiment.polarity == 0: 
        return 'neutral'
    else: 
        return 'negative'

In [28]:
tweets['sentiment'] = tweets['text'].apply(get_tweet_sentiment)

In [33]:
tweets.head()

,Unnamed: 0,datetime,time,is_reply,is_retweet,medias,nbr_favorite,nbr_reply,nbr_retweet,text,url,user_id,usernameTweet,sentiment
0,0,2018-06-01,04:17:57,False,False,NaN,0,0,0,Typically your 6th sense is the best indicator...,/RakBukuIkhwan/status/1002283057292886016,996819257227857920,RakBukuIkhwan,positive
1,1,2018-06-22,21:08:30,False,False,NaN,2,0,1,# SapuraEnergy in nine #offshore deals worth...,/offshoreenergyt/status/1010147515876995073,125821523,offshoreenergyt,positive
2,2,2018-06-23,18:20:19,False,False,['https://t.co/Oh7fBVGUkU'],0,0,0,# NewsUpdate : #SapuraEnergy bags contracts w...,/EnergyDais/status/1010467581218598912,892323207750926336,EnergyDais,positive
3,3,2018-07-09,00:06:13,False,False,NaN,0,0,0,# zurieeahmadconcepts crew dubbed as #hokacre...,/strogayah/status/1015990446001217536,90175802,strogayah,neutral
4,4,2018-07-09,21:56:08,False,False,NaN,0,0,0,09/07/2018 - “ Great things in business are ne...,/syazwanHairey/status/1016320097835773952,161169232,syazwanHairey,positive

In [34]:
#export the output file as excel
Sentiment = pd.DataFrame(tweets).to_excel('sapuraSA.xlsx')